### ISSUE TITLE
Cannot import any utility functions

### ISSUE THREAD

**Issue by viralpandey** [ilanschnell/bitarray#180] opened 2022-09-26 18:28 UTC
Hey! When importing any functions from the `bitarray.util`, I am getting the following error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-141-4a193a4c35ff> in <module>
----> 1 from bitarray.util import serialize

ImportError: cannot import name 'serialize' from 'bitarray.util' (/opt/anaconda3/lib/python3.8/site-packages/bitarray/util.py)
```

I am using the latest version of the module. Can you help me with this? Thank you.

**Comment by ilanschnell** [comment] 2022-09-26 22:55
Thanks for using bitarray, and reporting this issue.  The function you are trying to use was added in version 1.8.  Are you sure you are using the latest version?  What it the output when you do:
```
import bitarray
print(bitarray.__version__)
```
The function `serialize` is defined in `bitarray._util`.  Can you `import bitarray.util`?

**Comment by viralpandey** [comment] 2022-09-27 17:07
@ilanschnell I am using the latest `2.6.0` version. I tried `_util` as well but that didn't work either. These are the files that were downloaded when I did `pip install bitarray`.
<img width="232" alt="image" src="https://user-images.githubusercontent.com/11019702/192591065-324a3998-4486-4c78-bbcf-458b80dd7644.png">

**Comment by ilanschnell** [comment] 2022-09-27 22:01
This is very strange.  In your output I see `_util.cpython-38-darwin.so`, so `import bitarray._util` should work, unless the file has the wrong permissions or is somehow corrupted.  I've created a Python 3.8 environment, and did `pip install bitarray` and found no problems.  I would try to remove bitarray, and then reinstall it.

**Comment by ilanschnell** [comment] 2022-10-13 22:59
As I cannot reproduce the problem, I'm closing the issue for now.  Please feel free to reopen if the problem persists or if you have any updates.

**Closed by ilanschnell** 2022-10-13 22:59 UTC
